spring.application.name=sees

spring.datasource.url=jdbc:mysql://localhost:3306/sees?useSSL=false&serverTimezone=America/Recife&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

server.servlet.context-path=/sees
